name: Synk

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/snyk.yml
      - '**.py'
      - '**/requirements*.txt'
    paths-ignore:
      - '**.json'
      - '**.md'

defaults:
  run:
    shell: bash

jobs:
  security:
    name: Run Snyk to check for vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.8@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --severity-threshold=high --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
